services:
  - type: web
    name: zeeva-nails
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_NAME
        value: "Zeeva Nails"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:TbQtIVidbQi4Jht7uBpljpHkTXnCNOOH1nZsrwRj5uo=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://zeeva-nails.onrender.com
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: PHP_CLI_SERVER_WORKERS
        value: "4"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug

      # PostgreSQL Database Configuration
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d31kfjruibrs7392oucg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: zeeva_nails
      - key: DB_USERNAME
        value: zeeva_nails
      - key: DB_PASSWORD
        value: wQJmbjxvU62ymST1aFUzE04ycN2fvKq9
      - key: DB_AUTHENTICATION_DATABASE
        value: admin

      # Sessions, Cache, Queue
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_ENCRYPT
        value: "false"
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database

      # Redis (Optional - Not active unless configured)
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: "6379"

      # Mail (adjust if using actual mailer)
      - key: MAIL_MAILER
        value: log
      - key: MAIL_SCHEME
        value: null
      - key: MAIL_HOST
        value: 127.0.0.1
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: "Zeeva Nails"

      # AWS (not in use but declared)
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "false"

      # Vite config
      - key: VITE_APP_NAME
        value: "Zeeva Nails"
